title: Yujung Kim
description: Junior Software Engineer, Game Developer
site_title: '@Yujxxng Portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Yujxxng
email: ujungg3@gmail.com


# absolute or relative
profile_picture: assets/images/pp.png

# Google Analytics ID
google_analytics: 